//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_ItemOut
    {
        public int ID_ItemOut { get; set; }
        public Nullable<int> ID_ItemIn_fk { get; set; }
        public string BarCode { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ID_MS { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual POS_ItemIn POS_ItemIn { get; set; }
        public virtual POS_MasterSale POS_MasterSale { get; set; }
    }
}
