//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_ItemIn
    {
        public POS_ItemIn()
        {
            this.POS_ItemOut = new HashSet<POS_ItemOut>();
        }
    
        public int ID_ItemIn { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string BarCode { get; set; }
        public string HoleSalePrice { get; set; }
        public string RetailPrice { get; set; }
        public string Discount { get; set; }
        public string Quantity { get; set; }
        public string Description { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ICollection<POS_ItemOut> POS_ItemOut { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
