//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_MasterSale
    {
        public POS_MasterSale()
        {
            this.POS_ItemOut = new HashSet<POS_ItemOut>();
        }
    
        public int ID_MS { get; set; }
        public string MS_Code { get; set; }
        public Nullable<System.DateTime> Detetime { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> No_of_Item { get; set; }
        public Nullable<decimal> Net_Amount { get; set; }
        public Nullable<decimal> Cash_Rcv { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Change_due { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual ICollection<POS_ItemOut> POS_ItemOut { get; set; }
    }
}
