//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orgcode
    {
        public int Org_Id { get; set; }
        public string Name { get; set; }
        public string Cell { get; set; }
        public string Phone { get; set; }
        public string NIC { get; set; }
        public string Adress { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public string Licence_from { get; set; }
        public string Licence_to { get; set; }
        public string notice_Msg { get; set; }
        public string description { get; set; }
        public Nullable<int> log { get; set; }
        public Nullable<int> User_Log { get; set; }
        public string Licence_Key { get; set; }
        public string email { get; set; }
    }
}
