//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Designation
    {
        public tbl_Designation()
        {
            this.tbl_Employee = new HashSet<tbl_Employee>();
        }
    
        public int DesigID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsActive { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual ICollection<tbl_Employee> tbl_Employee { get; set; }
    }
}
