//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bank
    {
        public tbl_Bank()
        {
            this.tbl_Account = new HashSet<tbl_Account>();
        }
    
        public int BankId { get; set; }
        public string Name { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string isDelete { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual ICollection<tbl_Account> tbl_Account { get; set; }
    }
}
