//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanPerson
    {
        public tbl_LoanPerson()
        {
            this.tbl_Loan_Transactions = new HashSet<tbl_Loan_Transactions>();
        }
    
        public int LoanPersonID { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string NIC { get; set; }
        public string Description { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual ICollection<tbl_Loan_Transactions> tbl_Loan_Transactions { get; set; }
    }
}
