//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vendor_Payment
    {
        public tbl_Vendor_Payment()
        {
            this.tbl_Vendors_Mst_Transaction = new HashSet<tbl_Vendors_Mst_Transaction>();
        }
    
        public int Ven_Payment_ID { get; set; }
        public Nullable<int> Bill_ID { get; set; }
        public string Payment_Type { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public string Description { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Recv_Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Vendor tbl_Vendor { get; set; }
        public virtual ICollection<tbl_Vendors_Mst_Transaction> tbl_Vendors_Mst_Transaction { get; set; }
    }
}
