//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account
    {
        public tbl_Account()
        {
            this.tbl_Payment_Rcv = new HashSet<tbl_Payment_Rcv>();
            this.tbl_Vendor_Payment = new HashSet<tbl_Vendor_Payment>();
        }
    
        public int BankAccountId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string AccountTitle { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string ChequeBookStart { get; set; }
        public string ChequeBookEnd { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string isDelete { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual tbl_Bank tbl_Bank { get; set; }
        public virtual ICollection<tbl_Payment_Rcv> tbl_Payment_Rcv { get; set; }
        public virtual ICollection<tbl_Vendor_Payment> tbl_Vendor_Payment { get; set; }
    }
}
