//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stock
    {
        public tbl_Stock()
        {
            this.tbl_SaleDetail = new HashSet<tbl_SaleDetail>();
        }
    
        public int Stock_ID { get; set; }
        public Nullable<int> StockMstId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string PurchaseType { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Unit_Amount { get; set; }
        public Nullable<decimal> Sale_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string PurchaseStatus { get; set; }
    
        public virtual ICollection<tbl_SaleDetail> tbl_SaleDetail { get; set; }
        public virtual tbl_SalesTypeSetupForm tbl_SalesTypeSetupForm { get; set; }
        public virtual tbl_StockMst tbl_StockMst { get; set; }
        public virtual tbl_Vendor tbl_Vendor { get; set; }
    }
}
