//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public tbl_Employee()
        {
            this.tbl_Customer = new HashSet<tbl_Customer>();
            this.tbl_Payment_Rcv = new HashSet<tbl_Payment_Rcv>();
            this.tbl_SaleMaster = new HashSet<tbl_SaleMaster>();
            this.tbl_Account_Mst_Transaction = new HashSet<tbl_Account_Mst_Transaction>();
        }
    
        public int EmpID { get; set; }
        public Nullable<int> DesignID { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string CellNo { get; set; }
        public string NIC { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PhoneNo { get; set; }
        public string IsActive { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string description { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<tbl_Customer> tbl_Customer { get; set; }
        public virtual tbl_Designation tbl_Designation { get; set; }
        public virtual ICollection<tbl_Payment_Rcv> tbl_Payment_Rcv { get; set; }
        public virtual ICollection<tbl_SaleMaster> tbl_SaleMaster { get; set; }
        public virtual ICollection<tbl_Account_Mst_Transaction> tbl_Account_Mst_Transaction { get; set; }
    }
}
