//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account_Mst_Transaction_Backup
    {
        public long Acc_Trans_ID { get; set; }
        public Nullable<int> SaleMst_ID { get; set; }
        public Nullable<int> ExpMstID { get; set; }
        public string Particular { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<decimal> DR_Amount { get; set; }
        public Nullable<decimal> CR_Amount { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<long> FkAcc_Trans_ID { get; set; }
    }
}
