//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MstExpense
    {
        public tbl_MstExpense()
        {
            this.tbl_ExpenseDetail = new HashSet<tbl_ExpenseDetail>();
            this.tbl_Account_Mst_Transaction = new HashSet<tbl_Account_Mst_Transaction>();
        }
    
        public int ExpMstID { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string Expensetype { get; set; }
    
        public virtual ICollection<tbl_ExpenseDetail> tbl_ExpenseDetail { get; set; }
        public virtual ICollection<tbl_Account_Mst_Transaction> tbl_Account_Mst_Transaction { get; set; }
    }
}
