//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceInfo
    {
        public long ID { get; set; }
        public string CompanyName { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string Addressline3 { get; set; }
        public string footer1 { get; set; }
        public string footer2 { get; set; }
        public string footer3 { get; set; }
        public string PoweredBy { get; set; }
        public string Note { get; set; }
        public string isactive { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string fields1 { get; set; }
        public string fields2 { get; set; }
        public string fields3 { get; set; }
        public string fields4 { get; set; }
        public string bodywidh { get; set; }
        public string contentwidth { get; set; }
        public string fontsize { get; set; }
    }
}
