//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loan_Transaction_Backup
    {
        public int Loan_Backup_ID { get; set; }
        public Nullable<int> LoanPersonID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string LoanType { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string Durantion { get; set; }
        public string Description { get; set; }
        public string Payment_Type { get; set; }
        public Nullable<decimal> DR_Amount { get; set; }
        public Nullable<decimal> CR_Amount { get; set; }
        public string Loan_Purpose { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
    }
}
