//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string CellNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string NIC { get; set; }
        public string IsActive { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
