//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RateList
    {
        public long RateListID { get; set; }
        public Nullable<int> SaleTypeID_ItemId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string Updateby { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_SalesTypeSetupForm tbl_SalesTypeSetupForm { get; set; }
    }
}
