//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vendor
    {
        public tbl_Vendor()
        {
            this.tbl_StockMst = new HashSet<tbl_StockMst>();
            this.tbl_Stock = new HashSet<tbl_Stock>();
            this.tbl_Vendors_Mst_Transaction = new HashSet<tbl_Vendors_Mst_Transaction>();
            this.tbl_Vendor_Payment = new HashSet<tbl_Vendor_Payment>();
        }
    
        public int VendorId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public string Contact_Person { get; set; }
        public string Cell { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual ICollection<tbl_StockMst> tbl_StockMst { get; set; }
        public virtual ICollection<tbl_Stock> tbl_Stock { get; set; }
        public virtual ICollection<tbl_Vendors_Mst_Transaction> tbl_Vendors_Mst_Transaction { get; set; }
        public virtual ICollection<tbl_Vendor_Payment> tbl_Vendor_Payment { get; set; }
    }
}
