//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesTypeSetupForm
    {
        public tbl_SalesTypeSetupForm()
        {
            this.tbl_SaleDetail = new HashSet<tbl_SaleDetail>();
            this.tbl_Stock = new HashSet<tbl_Stock>();
            this.tbl_RateList = new HashSet<tbl_RateList>();
        }
    
        public int SaleTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsActive { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Total { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
    
        public virtual tbl_Brand tbl_Brand { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual ICollection<tbl_SaleDetail> tbl_SaleDetail { get; set; }
        public virtual ICollection<tbl_Stock> tbl_Stock { get; set; }
        public virtual ICollection<tbl_RateList> tbl_RateList { get; set; }
    }
}
