//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        public tbl_Category()
        {
            this.tbl_SalesTypeSetupForm = new HashSet<tbl_SalesTypeSetupForm>();
            this.POS_ItemIn = new HashSet<POS_ItemIn>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsActive { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual ICollection<tbl_SalesTypeSetupForm> tbl_SalesTypeSetupForm { get; set; }
        public virtual ICollection<POS_ItemIn> POS_ItemIn { get; set; }
    }
}
