//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleMaster
    {
        public tbl_SaleMaster()
        {
            this.tbl_SaleDetail = new HashSet<tbl_SaleDetail>();
        }
    
        public int SaleMst_ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public string Discount__ { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public Nullable<long> invoiceid { get; set; }
    
        public virtual ICollection<tbl_SaleDetail> tbl_SaleDetail { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
