//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StockMst
    {
        public tbl_StockMst()
        {
            this.tbl_Stock = new HashSet<tbl_Stock>();
            this.tbl_Vendors_Mst_Transaction = new HashSet<tbl_Vendors_Mst_Transaction>();
        }
    
        public int StockMstId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> Org_Id { get; set; }
    
        public virtual tbl_Vendor tbl_Vendor { get; set; }
        public virtual ICollection<tbl_Stock> tbl_Stock { get; set; }
        public virtual ICollection<tbl_Vendors_Mst_Transaction> tbl_Vendors_Mst_Transaction { get; set; }
    }
}
